fragments = [
    // Ending 1 - Dream
    {"answer": "Yes, I am sure. All our satellites confirm this.", "answers":[["Do we know why did they attack?", 1]], "type":1},
    {"answer": "The launch was detected only minutes after our military exercises began. Maybe just a misunderstanding. Sadly we cannot do anything about that now.", "answers":[["What can we do?", 2]], "type":1},
    {"answer": "Not much. Our interceptors are going to be launched automatically, they may stop 30 warheads, but majority will make it through. Only thing we can do, is retaliate.", "answers":[["What would we achieve?", 3]], "type":1},
    {"answer": "Only 37 out of the 93 known missle silos of the enemy have launched their missles. We can neutralise them, and prevent further exchange.", "answers":[["Are they only feasable target?", 4]], "type":1},
    {"answer": "We could also target their infrastructure. Lot of it is concentrated near or in their major population centers. Therefore, as a side effect, we would cause a lot of casualties to the enemy.", "answers":[["With what can we retaliate right now?", 5]], "type":1},
    {"answer": "We have around 1600 warheads. 750 in our ICBMs, 250 in our submarines, and 600 in our bombers. About 300 bombers are able to take off in around 2 minutes, if you give the order now. Majority of our submarines are currently docked, though we have 10 deployed. They are practically undetectable, while they are submerged. So that's our backup.", "answers":[["How much time do I have to make the decision?", 6]], "type":1},
    {"answer": "Like I said, our submarines are currently our backup, so we have time with them. Our bombers need 2 minutes to launch, and another 5 to get out of the blast radius, if their base is targeted. To launch our ICBMs, you need to give the order NOW. It takes around 3 minutes to order and confirm a launch and another 2 to launch. We have some extra time, though sooner we order the launch, the better, in a few minutes, our communications may not work.", "answers":[["Launch the ICBMs", 7], ["Can we contact them?",48]], "type":1}, // Possible point of divergence Ending 1/2
    {"answer": "Understood! Please state the launchcode.", "answers":[["I do not remember them.", 8]], "type":1},
    {"answer": "Thats bad. They should be in your handbook, Sir.", "answers":[["Handbook?", 9]], "type":1},
    {"answer": "Yes, handbook. I completely forgot it's your first day in office. It should be in your upper drawer.", "answers":[["Okay, I have it.", 10]], "effect":"foundHandbook", "type":1},
    {"answer": "Perfect. The launchcode should be there. Are you ready to state the launchcode now, Sir?", "answers": [["Yes, I am.", 11]], "type":1},
    {"answer": "I am listening, Sir!", "answers": [["1134 2347 9976", 12], [(((Math.round(Math.random()*9999)).toString()) + " " + ((Math.round(Math.random()*9999)).toString()) + " " + ((Math.round(Math.random()*9999)).toString())), 12], [(((Math.round(Math.random()*9999)).toString()) + " " + ((Math.round(Math.random()*9999)).toString()) + " " + ((Math.round(Math.random()*9999)).toString())), 12], [(((Math.round(Math.random()*9999)).toString()) + " " + ((Math.round(Math.random()*9999)).toString()) + " " + ((Math.round(Math.random()*9999)).toString())), 12]], "type":1},
    {"answer": "Perfect, Sir. Our ICMBs will launch shortly.", "answers":[["What about everything else?", 13]], "type":1},
    {"answer": "We have $rem_minutes$ minutes. We can launch our bombers, though our docked submarines are basically sitting ducks now.", "answers":[["Launch the bombers.", 14]], "type":1},
    {"answer": "Understood! Can you state the launchphrase? It should also be in your handbook.", "answers":[["Sure. Machine, Air, Underground", 15]], "type":1},
    {"answer": "The bombers are on their way, Sir. That's all we can do for now. We just have to wait.", "answers":[["That's all? There isn't anything else we can do? What about our citizes?", 16]], "type":1},
    {"answer": "Yes that's all, Sir. All TV and Radio stations have been broadcasting to the citizens about the incoming strikes alongside the sirens, also all EWS compatible devices have received a warning. All citizens have been ordered to shelter.", "answers":[["Well, at least something. And what about me?", 17]], "type":1},
    {"answer": "You should be safe in your bunker, Sir.", "answers":[["Bunker?", 18]], "type":1},
    {"answer": "You aren't in your bunker, Sir?!", "answers":[["No, I am not. Where is it?", 19]], "type":1},
    {"answer": "Quickly, Sir! There should be...", "answers": [["There should be what? Can you hear me?", 20]], "type":1},
    {"answer": "[Noise]", "answers": [["What now? Maybe the handbook will have answers!", 21]], "type":2},
    {"answer": "If you are reading this...", "answers": [["Well, that was not very useful.", 22]], "type":2},
    {"answer": "You remember that this morning you were given today's newspaper. Maybe something useful will be there?", "answers":[["What? We lost again?", 22], ["A secret item?", 23], ["A new AstroBattle movie?", 22]], "type":2, "effect":"foundNewspaper"},
    {"answer": "The charger has no logos, no text, it's as if it was fake.", "answers":[["I am sure this is the secret item!", 24], ["Charging my phone is the last thing to do in this situation.", 23]], "type": 2},
    {"answer": "You take closer look at the charger. Only thing on it is a pictogram of charger in a plug.", "answers":[["There is a plug here. Maybe putting it in is what I am supposed to do.", 25], ["As if anyone wouldnt know how to use charger!", 24]], "type": 2},
    {"answer": "You put the plug in the charger. Your whole table starts going underground. In a moment you are in a bunker.", "answers":[["Maybe this is what the chief of security wanted to show me this morning. I should have listened.", 25], ["This is surely the bunker!", 26]], "type":2},
    {"answer": "The lights turn on. You see monitors with info from the military. Radars and much more. As everything settels, you hear the phone ring and you pick it up.", "answers":[["Who's there?", 27], ["Yeah?", 27]], "type":2},
    {"answer": "Oh, you are alive, Sir!", "answers":[["Who's there again?", 29], ["I am?!", 28]], "type":1},
    {"answer": "I am going to act as if that weird and quite unnecessary joke didn't happen.", "answers":[["Oh, okay. Who's there again?", 29]], "type":1},
    {"answer": "It's me, the Minister of Defence.", "answers":[["Oh, I though you were dead.",30]], "type":1},
    {"answer": "I thought the same about you, Sir.", "answers":[["Well, I am not.", 31]], "type":1},
    {"answer": "That's bad. That's really bad...", "answers":[["I am glad to hear from you also.", 32]], "type":1},
    {"answer": "Oh, sorry Sir. I didn't mean it like that!", "answers":[["Well, then how did you meant it?", 33]], "type":1},
    {"answer": "Well, I assumed you were dead, as the protocols require me to.", "answers":[["And?", 34]], "type":1},
    {"answer": "I've authorized a full-scale nuclear attack on the enemy. We have only a few seconds left. Do you want to cancel it?", "answers":[["Yes! Cancel the attack immidetly!", 35]], "type":1},
    {"answer": "Sure Sir. Consider the attack canceled. Also, we now have confirmations of the warheads entering our airspace, they will detonate shortly.", "answers":[["What about the bombers? Are they out of the blast radius?", 36]], "type":1},
    {"answer": "You hear loud explosion.", "answers":[["Gosh, what was that?", 37], ["Do you hear me?", 37]], "type":2},
    {"answer": "That was a first bomb. It's now or never. We have 283 bombers airborne, 10 submarines deployed, and about 93 ICBMs still able to launch. Do we retaliate?", "answers":[["Yes, attack with all we that have.", 38],["It is not worth it.", 55]], "type":1},  // Possible point of divergence Ending 1/2
    {"answer": "Understood, Sir! Our first bombs should land on the enemies teritory shortly.", "answers":[["What now?", 39]], "type":1},
    {"answer": "Nothing, Sir! That's all that we cloud do.", "answers":[["Will anyone survive this?", 40]], "type":1},
    {"answer": "I doubt it Sir. Who won't be killed by the explosion or the radiation, will die because of the nuclear winter.", "answers":[["So, that's all? Is this end of humanity?", 41]], "type":1},
    {"answer": "[NOISE]", "answers":[["Are you there?", 42]], "type":2},
    {"answer": "You get no response", "answers":[["Well, thats it. I am responsible for death of billions. And what did I achieve?", 43]], "type":2},
    {"answer": "You hear a loud explosion and before you can react, you are nothing more than dust.", "answers":[["AHHHHHHHH", 44]], "type":2, "effect":"disableTimer"},
    {"answer": "Honey? HONEY!", "answers":[["What?! You aren't dead?", 45]], "type":1},
    {"answer": "Why would I be?", "answers":[["Well, he said that the bombs will be here in few mintues!", 46]], "type":1},
    {"answer": "What bombs? Who did say that?", "answers":[["The minister of defense!", 47]], "type":1},
    {"answer": "Oh, honey. You had a nightmare. Go to sleep again. Tomorow is your first day as president, you got to be well rested!", "answers":[["Oh, so it was a dream?", 10001]], "type":1},
    // Ending 2 - No retaltation
    {"answer": "I am not sure. We may try though.", "answers":[["Try it, IMMIDIETLY!", 49], ["There is no time to waste. Launch the ICBMs!", 7]], "type":1},
    {"answer": "I will do my best, Sir!", "answers":[["Call me immidietly if they respond!", 50], ["You know what? There is no time to waste. Launch the ICBMs!", 7]], "type":1},
    {"answer": "Minister of Defense hungs up the phone. You are sitting in your office, hearing the sirens from outside. After what feels like eternity, your phone once again rings, you pick it up and hear your Minister of Defense.", "answers":[["Did they answer?",52], ["I've changed my mind!", 51]], "type":2},
    {"answer": "Oh, okay. What should we do?", "answers":[["Launch the ICBMs!", 7], ["Order the bombers airborne!", 14], ["Wait. I am panicking a bit. What did you want to say?", 52]], "type":2},
    {"answer": "The line seems to be damaged. There is no way to contact them!", "answers":[["Destroy them.", 7], ["Tell me once again. What would we achieve with retaliation.", 53]], "type":1},
    {"answer": "We cannot stop the rockets coming at us. Only thing we can do is the same thing they can do to us. Destroy everything that would make them capable of continuing this war, making it over, before it even began.", "answers":[["Return the fire.", 7], ["So, only thing we would achieve is more civilian deaths?", 54]], "type":1},
    {"answer": "Basically yes. Though if nuclear winter ensues, it does not matter if we launch or not, billions will die.", "answers": [["We do not have any other option.",7],["It is not worth it.", 55]], "type":1},
    {"answer": "I am confused sir. What are your orders?", "answers":[["I do not authorise any launch or attack. Do not call me again!", 56]], "type":1},
    {"answer": "You hang up the phone. You take one last look at the photo of your family and wait for those $rem_minutes$ minutes.", "answers":[["...",10002]], "type":2, "effect":"disableTimer"},
]

endings = [
    {"answer": "Yeah, it was just a dream.", "answers":[["Oh, thank god!", 99990]], "type":1},
    {"answer": "As you are looking at the photo, warhead explodes just above your office, evaporating you in a fraction of a second.", "answers":[["...",99991]], "type":2}
]
